import type { Metadata } from 'next';
import { Open_Sans, Noto_Sans_SC, Source_Sans_3 } from 'next/font/google';
import './globals.css';

const open = Open_Sans({ variable: '--font-open', subsets: ['latin'] });
const noto = Noto_Sans_SC({ variable: '--font-noto', subsets: ['latin'] });
const source = Source_Sans_3({ variable: '--font-source', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${open.variable} ${noto.variable} ${source.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
